modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory 
issueTrackerURL="" #optional
license="see license file"

[[mods]] #mandatory
modId="biomeadjuster" #mandatory
logoFile="tg_icon.png"
logoBlur=false
version="${file.jarVersion}" #mandatory
displayName="biomeadjuster" #mandatory
authors="TelepathicGrunt"
description='''

'''

[[dependencies.biomeadjuster]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5, 1.17.0)"

[[dependencies.biomeadjuster]]
modId="forge"
mandatory=true
versionRange="[36.2.0,)"